### PR TITLE
Add support for course structure API queries

### PR DESCRIPTION
**Pull request by justinabrahms**
Allows us to query for course structure APIs. See integration test for more info.

### CODE REVIEW

**Comment by giocalitri** [comment]
:+1:

**Comment by giocalitri** [comment]
I think it is not necessary to squash (if the commits do exactly what their title says)

**Comment by pdpinch** [comment]
is codecov a replacement for coveralls?

**Comment by justinabrahms** [comment]
Yes. It's a better coveralls.

**Pull request merged**
