### PR TITLE
feat: add Verified mode enrollment creation

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### What are the relevant tickets?
https://github.com/mitodl/micromasters/issues/5193

#### What's this PR do?
- Adds a new function to create `Verified` mode enrollments

#### Where should the reviewer start?
- Installing it in the MM, And then enrolling a user with open edX.

#### How should this be manually tested?
- Install the client from this branch
- Enroll a user in `Verified` mode in edX course
- This will require integration of edX with MicroMasters

#### Any background context you want to provide?
More details are mentioned in https://github.com/mitodl/micromasters/issues/5193

**NOTE:** 
1 - This PR is based on `Verified` mode and I created this PR just in advance as we still need to finalize the mode to be used as mentioned in [this comment](https://github.com/mitodl/micromasters/issues/5193#issuecomment-1097914534)
2- This PR is currently not tested since I don't have a working local edX/MicroMasters integration.

### CODE REVIEW

**Comment by annagav** [comment]
@arslanashraf7 the code looks good, but in order to test this we need:
1) to merge this PR and release it
2) open a MM PR where we use this new function and upgrade `edx-api-client`

**Comment by arslanashraf7** [comment]
@annagav Can you approve the PR if it looks good to you?

@pdpinch, @rhysyngsun Any reservations from your side?

**Review by annagav — APPROVED** [review]
👍

**Comment by arslanashraf7** [comment]
So I'm going to merge this PR, We can address any reservations in a follow-up PR.

**Pull request merged**
